version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-poc
    environment:
      - RABBITMQ_DEFAULT_USER=scoth
      - RABBITMQ_DEFAULT_PASS=tiger
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mordor
  
  employee_api:
    image: employeeapi
    build:
      context: .
      dockerfile: EmployeeService/Dockerfile
    restart: on-failure
    ports:
      - 5226:5226
    depends_on:
      - rabbitmq
    networks:
      - mordor

  insurance_api:
    image: insuranceapi
    build:
      context: .
      dockerfile: InsuranceService/Dockerfile
    restart: on-failure
    ports:
      - 5011:5011
    depends_on:
      - rabbitmq
    networks:
      - mordor

  employee_webapp:
    image: employeewebapp
    build:
      context: .
      dockerfile: Employee.WebApp/Dockerfile
    restart: on-failure
    ports:
      - 5201:5201
    depends_on:
      - employee_api
    networks:
      - mordor

  insurance_webapp:
    image: insurancewebapp
    build:
      context: .
      dockerfile: Insurance.WebApp/Dockerfile
    restart: on-failure
    ports:
      - 5131:5131
    depends_on:
      - insurance_api
    networks:
      - mordor
  
networks:
  mordor:
    driver: bridge
